#!/usr/bin/env python
"""Slice 11a: one command, one table.

    python tasks.py evaluate

Runs the real OCR path over the fixture corpus and reports character error rate by
language, plus stage latency. It does NOT report extraction precision or recall -
`docs/PLAN.md` R9 cut that as self-referential, because the regex extractors were
written against documents this same generator produced, so precision would measure
agreement with ourselves.

Every caveat printed under the table is there because the number is easy to
over-read, not as decoration. Ten synthetic documents on one laptop is a measurement
of this corpus, and CLAUDE.md's ban on fabricated statistics covers a real figure
presented as more general than it is.
"""
import json
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from domain.accuracy import Measurement, aggregate, measure, percentile  # noqa: E402
from infra.textsource import TesseractOcr  # noqa: E402

CORPUS = ROOT / "fixtures" / "corpus"


def main() -> int:
    if not TesseractOcr.available():
        print("  tesseract is not installed - refusing to report a figure.")
        print("  Falling back to the embedded text layer would score ~0% CER and")
        print("  measure nothing (docs/adr/0012).")
        return 1

    pdfs = sorted(CORPUS.glob("*.pdf"))
    if not pdfs:
        print("  no corpus - run `python tasks.py fixtures` first")
        return 1

    ocr = TesseractOcr(languages="hin+eng")
    measurements: list[Measurement] = []
    latencies: list[float] = []
    per_document: list[tuple[str, str, float, float]] = []
    # Slice 6b split the corpus into clean renders and degraded scans. Averaging the
    # two into one figure would hide the only comparison worth having: a clean render
    # is not a scan, and the distance between them is the number to quote.
    by_condition: dict[str, list[Measurement]] = {"clean": [], "degraded": []}

    print(f"\n  measuring {len(pdfs)} documents with real OCR ...\n")
    for pdf in pdfs:
        sidecar = json.loads(pdf.with_suffix(".json").read_text(encoding="utf-8"))
        truth = "\n".join(page["text"] for page in sidecar["pages"])

        started = time.perf_counter()
        result = ocr.extract(pdf.read_bytes())
        elapsed = time.perf_counter() - started

        if result.method != "tesseract_ocr":
            # Should be unreachable; asserted rather than assumed because the whole
            # figure is void if a text-layer read slips in.
            print(f"  REFUSING: {pdf.name} was read by {result.method}, not OCR")
            return 1

        m = measure(
            document=pdf.stem, language=sidecar["language"], method=result.method,
            truth=truth, observed=result.text,
        )
        measurements.append(m)
        latencies.append(elapsed)
        per_document.append((pdf.stem, sidecar["language"], m.cer, elapsed))
        by_condition["degraded" if sidecar.get("degraded") else "clean"].append(m)

    # --- the table ---------------------------------------------------------
    print("  OCR character error rate, by language")
    print("  " + "-" * 62)
    print(f"  {'language':<10}{'documents':>11}{'chars':>10}{'errors':>9}{'CER':>10}")
    print("  " + "-" * 62)
    for language, bucket in sorted(aggregate(measurements).items()):
        print(
            f"  {language:<10}{bucket['documents']:>11}{bucket['truth_chars']:>10}"
            f"{bucket['errors']:>9}{bucket['cer'] * 100:>9.2f}%"
        )
    print("  " + "-" * 62)

    if by_condition["degraded"]:
        print("\n  clean renders vs degraded scans")
        print("  " + "-" * 62)
        print(f"  {'condition':<12}{'documents':>11}{'chars':>10}{'errors':>9}{'CER':>10}")
        print("  " + "-" * 62)
        for condition in ("clean", "degraded"):
            rows = by_condition[condition]
            if not rows:
                continue
            chars = sum(r.truth_chars for r in rows)
            errors = sum(r.errors for r in rows)
            print(
                f"  {condition:<12}{len(rows):>11}{chars:>10}{errors:>9}"
                f"{(errors / chars if chars else 0) * 100:>9.2f}%"
            )
        print("  " + "-" * 62)

    print("\n  per document")
    for name, language, cer, elapsed in per_document:
        print(f"    {name:<22}{language:<6}{cer * 100:>7.2f}%   {elapsed:>6.2f}s")

    print("\n  stage latency (OCR only)")
    print(f"    p50  {percentile(latencies, 50):>6.2f}s")
    print(f"    p95  {percentile(latencies, 95):>6.2f}s")
    print(f"    max  {max(latencies):>6.2f}s")

    # --- what the number is not --------------------------------------------
    print("\n  Read this as a measurement of this corpus, not an accuracy claim:")
    print(f"    - {len(pdfs)} synthetic documents, generated by this project, on one machine.")
    print("    - Ground truth is the text placed on the page before rendering, so")
    print("      Tesseract never saw it. The pipeline rasterises first, so this is")
    print("      OCR over pixels rather than a text layer compared with itself.")
    print("    - Hindi documents are mixed-script: the field labels and the reference")
    print("      number are Latin, as bilingual forms genuinely are. The 'hin' row is")
    print("      therefore not a pure Devanagari figure.")
    print("    - The degraded documents are tilted 0.8 degrees, rasterised at 120 dpi")
    print("      and speckled, with no text layer. That models resolution loss, skew")
    print("      and sensor noise. It does NOT model compression artefacts, uneven")
    print("      lighting, fold lines, handwriting or camera perspective, so it is a")
    print("      floor on how much worse real paper is rather than an estimate of it.")
    print("    - Extraction precision is deliberately absent: the extractors were")
    print("      written against documents this generator produced, so the figure")
    print("      would measure agreement with ourselves (PLAN R9).")
    print()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
